FROM node:22.14.0-alpine3.21

WORKDIR /srv/app

RUN npm install -g @nestjs/cli

COPY . .

RUN npm install && \
    npm cache clean --force && \
    rm -rf /tmp/* /root/.npm /root/.cache

CMD ["npm", "run", "start:dev"]
